# Generated by Django 3.2 on 2023-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read the blog post......', max_length=255),
        ),
    ]
